# Generated by Django 5.0.6 on 2024-06-24 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('prospect', 'prospect'), ('lead', 'lead'), ('customer', 'customer')], default='prospect', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000)),
                ('tag', models.CharField(choices=[('prospect', 'prospect'), ('lead', 'lead'), ('customer', 'customer')], default='prospect', max_length=50)),
            ],
        ),
    ]
